const products = [
  { id: 'pack', name: 'Ridgeline Trail Pack', type: 'Travel', price: 128, color: 'sage', icon: '▱' },
  { id: 'jacket', name: 'Field Jacket No. 7', type: 'Apparel', price: 184, color: 'sand', icon: '◒' },
  { id: 'mug', name: 'Enamel Camp Mug', type: 'Camp', price: 24, color: 'orange', icon: '◍' },
  { id: 'lantern', name: 'Ridge Lantern', type: 'Camp', price: 68, color: 'blue', icon: '◉' },
  { id: 'blanket', name: 'North Coast Blanket', type: 'Home', price: 96, color: 'plum', icon: '▧' },
  { id: 'tote', name: 'Utility Market Tote', type: 'Travel', price: 42, color: 'yellow', icon: '⌑' },
  { id: 'tee', name: 'Merino Everyday Tee', type: 'Apparel', price: 54, color: 'green', icon: '▤' },
  { id: 'chair', name: 'Folding Camp Chair', type: 'Camp', price: 118, color: 'red', icon: '⌁' },
];
const state = { route: location.hash.slice(1) || 'home', product: 'pack', category: 'All', query: '', cart: [], error: null, correlation: null };
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
const money = value => `$${Number(value).toFixed(2)}`;
const getProduct = () => products.find(p => p.id === state.product) || products[0];
const count = () => state.cart.reduce((n, p) => n + p.qty, 0);
const total = () => state.cart.reduce((n, p) => n + p.price * p.qty, 0);
function save() { localStorage.setItem('mtb-ui', JSON.stringify({ cart: state.cart, error: state.error, correlation: state.correlation })); }
try { Object.assign(state, JSON.parse(localStorage.getItem('mtb-ui') || '{}')); } catch (_) {}
function go(route) { state.route = route; location.hash = route; render(); window.scrollTo(0, 0); }
function notice(text, bad = false) { const el = document.createElement('div'); el.className = `notice ${bad ? 'bad' : ''}`; el.textContent = text; document.body.appendChild(el); setTimeout(() => el.remove(), 2400); }
let operatorTapCount = 0;
let operatorTapTimer;
function operatorTap() { operatorTapCount += 1; clearTimeout(operatorTapTimer); operatorTapTimer = setTimeout(() => { operatorTapCount = 0; }, 1800); if (operatorTapCount >= 7) { operatorTapCount = 0; openOperator(); } }
function operatorStatus(text, bad = false) { const el = $('operator-status'); if (!el) return; el.textContent = text; el.className = `operator-status ${bad ? 'bad' : ''}`; }
function openOperator() { if ($('operator-overlay')) return; const overlay = document.createElement('div'); overlay.id = 'operator-overlay'; overlay.className = 'operator-overlay'; overlay.innerHTML = `<div class="operator-backdrop" onclick="closeOperator()"></div><section class="operator-panel" role="dialog" aria-modal="true" aria-labelledby="operator-title"><button class="operator-close" onclick="closeOperator()" aria-label="Close operator controls">×</button><small>Private operator control</small><h2 id="operator-title">Reliability switch</h2><p>Use this only for an incident simulation. The public storefront stays available so the switch can be restored.</p><label>Operator key<input id="operator-key" type="password" autocomplete="off" placeholder="Enter the configured key" /></label><div id="operator-status" class="operator-status">Enter the operator key to continue.</div><div class="operator-actions"><button class="btn dark" onclick="operatorAction(true)">Take website down</button><button class="btn" onclick="operatorAction(false)">Restore website</button></div></section>`; document.body.appendChild(overlay); $('operator-key').focus(); }
function closeOperator() { $('operator-overlay')?.remove(); }
async function operatorAction(enabled) { const key = $('operator-key')?.value.trim(); if (!key) return operatorStatus('Operator key is required.', true); operatorStatus('Updating availability…'); try { const response = await fetch('/api/outage', { method: 'POST', headers: { 'content-type': 'application/json', 'x-breaker-key': key }, body: JSON.stringify({ enabled, reason: 'Operator-triggered website availability simulation' }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Operator request failed'); operatorStatus(enabled ? 'Synthetic outage is enabled. Health checks should now fail.' : 'Website availability restored.'); notice(enabled ? 'Synthetic outage enabled' : 'Website restored'); } catch (error) { operatorStatus(error.message, true); } }
function add(id = state.product) { const p = products.find(x => x.id === id); const found = state.cart.find(x => x.id === id); found ? found.qty++ : state.cart.push({ ...p, qty: 1 }); save(); notice(`${p.name} added to your bag`); render(); }
function remove(id) { state.cart = state.cart.filter(x => x.id !== id); save(); render(); }
function clearError() { state.error = null; save(); render(); }
function correlation() { return `cor_${Math.random().toString(36).slice(2, 9)}`; }
async function api(path, options = {}) {
  const cid = correlation(); state.correlation = cid; save();
  const response = await fetch(path, { ...options, headers: { 'content-type': 'application/json', 'x-correlation-id': cid, ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) { state.error = { message: data.message || 'Something went wrong. Please try again.', correlation: data.correlationId || cid, status: response.status }; save(); render(); throw new Error(data.error || 'request_failed'); }
  return data;
}
async function search() { try { await api(`/api/search?q=${encodeURIComponent(state.query)}`); } catch (_) {} state.route = 'search'; location.hash = 'search'; render(); }
async function checkout() { try { await api('/api/checkout', { method: 'POST', body: JSON.stringify({ items: state.cart }) }); } catch (_) {} }
async function profileSave() { try { await api('/api/profile', { method: 'PUT', body: JSON.stringify({ name: 'Puru Sharma' }) }); } catch (_) {} }
async function exportData() { try { await api('/api/exports', { method: 'POST', body: JSON.stringify({ format: 'csv' }) }); } catch (_) {} }
async function refresh() { try { await api('/api/session/refresh', { method: 'POST' }); } catch (_) {} }
async function supportSend() { try { await api('/api/support', { method: 'POST', body: JSON.stringify({ message: 'Customer support request' }) }); notice('Message sent — we will be in touch'); } catch (_) {} }
function report() { if (!state.error) return notice('Use the website until an error appears first', true); notice(`Issue reported with reference ${state.error.correlation}`); }
function downloadLogs() { fetch('/api/logs').then(r => r.json()).then(data => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(data.events || [], null, 2)], { type: 'application/json' })); a.download = 'meant-to-break-events.json'; a.click(); }); }

function header() { return `<header><div class="head"><a class="logo" href="#home" onclick="go('home');return false"><b>M</b>Meant to Break</a><nav><a href="#shop" onclick="go('shop');return false">Shop</a><a href="#categories" onclick="go('categories');return false">Categories</a><a href="#about" onclick="go('about');return false">Our story</a><a href="#help" onclick="go('help');return false">Help</a></nav><div class="head-right"><form onsubmit="event.preventDefault();state.query=this.q.value;search()"><span>⌕</span><input name="q" value="${esc(state.query)}" placeholder="Search" /></form><a href="#account" onclick="go('account');return false">Account</a><a href="#cart" onclick="go('cart');return false">Bag <i>${count()}</i></a></div></div></header>`; }
function footer() { return `<footer><div class="foot"><div><a class="logo light" href="#home" onclick="operatorTap();go('home');return false"><b>M</b>Meant to Break</a><p>Useful things for weekends away, slow mornings, and the spaces in between.</p></div><div><strong>Explore</strong><a href="#shop" onclick="go('shop');return false">Shop all</a><a href="#categories" onclick="go('categories');return false">Categories</a><a href="#about" onclick="go('about');return false">Our story</a></div><div><strong>Care</strong><a href="#orders" onclick="go('orders');return false">Order status</a><a href="#help" onclick="go('help');return false">Help center</a><a href="#contact" onclick="go('contact');return false">Contact</a></div><div><strong>Stay in the loop</strong><p>New arrivals, studio notes, no noise.</p><input placeholder="Email address" onkeydown="if(event.key==='Enter'){notice('You are on the list');this.value=''}" /></div></div><div class="foot-bottom">© 2026 Meant to Break <span>Made for the everyday outside.</span></div></footer>`; }
function layout(content) { return `${header()}<main>${content}</main>${footer()}`; }
function heading(eyebrow, h1, copy, action = '') { return `<div class="heading"><div><small>${eyebrow}</small><h1>${h1}</h1><p>${copy}</p></div>${action}</div>`; }
function btn(text, action, cls = '') { return `<button class="btn ${cls}" onclick="${action}">${text}</button>`; }
function alertBox() { return state.error ? `<div class="alert"><b>Something went wrong</b><p>${esc(state.error.message)}</p><small>Reference <code>${esc(state.error.correlation)}</code></small><button onclick="report()">Report this issue</button><button class="x" onclick="clearError()">×</button></div>` : ''; }
function card(p) { return `<article class="product"><a href="#product" onclick="state.product='${p.id}';go('product');return false"><div class="pic ${p.color}"><span>${p.icon}</span><i>MB</i></div><div class="product-line"><div><b>${p.name}</b><small>${p.type}</small></div><strong>${money(p.price)}</strong></div><div class="stars">★ 4.8 <em>(86)</em></div></a><button class="add" onclick="add('${p.id}')">Add to bag</button></article>`; }
function home() { return layout(`<section class="hero"><div><small>Spring / Summer 2026</small><h1>Made for the<br/><em>long way around.</em></h1><p>Thoughtful goods for the everyday outside. Built to travel well, wear in beautifully, and stay with you for a while.</p><div>${btn('Shop the collection', "go('shop')", 'dark')}${btn('Explore our story', "go('about')")}</div><aside>◉ &nbsp; Loved by 12,000+ weekend people</aside></div><div class="hero-art"><div class="sun"></div><div class="mountain"></div><div class="mountain two"></div><strong>▱</strong><label>THE RIDGELINE<br/><small>EST. 2019 · COASTAL MAINE</small></label></div></section>${alertBox()}<section class="section"><div class="section-head"><div><small>The edit</small><h2>Good things, chosen slowly.</h2></div><a href="#shop" onclick="go('shop');return false">View all →</a></div><div class="grid">${products.slice(0,4).map(card).join('')}</div></section><section class="story"><div>◌</div><article><small>Less, but better</small><h2>Objects with a sense of place.</h2><p>We work with small makers and durable materials to create pieces that feel at home wherever you take them.</p><a href="#about" onclick="go('about');return false">Read our story →</a></article></section><section class="section"><div class="section-head"><div><small>Browse by mood</small><h2>Where are you headed?</h2></div></div><div class="categories"><a class="travel" href="#category" onclick="state.category='Travel';go('category');return false"><b>Travel</b><span>Carry the essentials</span></a><a class="camp" href="#category" onclick="state.category='Camp';go('category');return false"><b>Camp</b><span>Make room for outside</span></a><a class="home" href="#category" onclick="state.category='Home';go('category');return false"><b>Home</b><span>Slow down in style</span></a></div></section>`); }
function shop() { const list = products.filter(p => state.category === 'All' || p.type === state.category); return layout(`${heading('Collection', 'Shop all', 'Find something useful.', btn('View categories', "go('categories')"))}<div class="shopbar"><div>${['All','Apparel','Travel','Camp','Home'].map(c => `<button class="${state.category === c ? 'chosen' : ''}" onclick="state.category='${c}';render()">${c}</button>`).join('')}</div><span>${list.length} pieces</span></div><div class="grid">${list.map(card).join('')}</div>`); }
function categories() { return layout(`${heading('Explore', 'Find your kind of outside.', 'Every collection has its own rhythm.', btn('Shop everything', "go('shop')", 'dark'))}<div class="category-large">${['Travel','Camp','Apparel','Home'].map((c,i) => `<a class="${c.toLowerCase()}" href="#category" onclick="state.category='${c}';go('category');return false"><b>${c}</b><span>${['Carry the essentials','Make room for outside','Wear the good stuff','Slow down in style'][i]}</span></a>`).join('')}</div>`); }
function category() { const list = products.filter(p => p.type === state.category); return layout(`${heading('Collection', state.category, 'A considered set of useful, well-made things.', btn('Back to all products', "state.category='All';go('shop')"))}<div class="grid">${list.map(card).join('')}</div>`); }
function product() { const p = getProduct(); return layout(`${alertBox()}<div class="detail"><div class="detail-pic ${p.color}"><span>${p.icon}</span><i>MB</i></div><div class="detail-copy"><small>${p.type} · ${p.id.toUpperCase()}</small><h1>${p.name}</h1><div class="stars">★ 4.8 <em>86 reviews</em></div><strong class="price">${money(p.price)}</strong><p>A dependable everyday piece, made with considered materials and a little room for the life that happens around it.</p><div class="choice"><b>Color</b><span class="swatch ${p.color}"></span> Field green</div><div class="choice"><b>Quantity</b><span class="quantity">− &nbsp; 1 &nbsp; ＋</span></div>${btn(`Add to bag · ${money(p.price)}`, `add('${p.id}')`, 'dark wide')}<div class="promises">✓ Free shipping over $75<br/>✓ 30-day easy returns<br/>✓ Made to be used, not displayed</div></div></div><div class="tabs"><div><b>Details</b><p>Designed in Portland and made in small batches with materials selected to age well.</p></div><div><b>Materials & care</b><p>Less washing, cool water, and a little patience.</p></div><div><b>Shipping</b><p>Orders leave our studio within two business days.</p></div></div>`); }
function searchPage() { return layout(`${heading('Search', state.query ? `Results for “${esc(state.query)}”` : 'Search the collection', 'Useful things, wherever you are.')}${alertBox()}<div class="search-results"><p class="muted">${state.query ? 'The catalog is looking for your request.' : 'Try searching for “pack”, “camp”, or “jacket”.'}</p><div class="grid">${(state.query ? products.filter(p => p.name.toLowerCase().includes(state.query.toLowerCase()) || p.type.toLowerCase().includes(state.query.toLowerCase())) : products.slice(0,4)).map(card).join('')}</div></div>`); }
function cart() { return layout(`${heading('Your bag', 'A few good things.', 'Review your selection before heading out.', state.cart.length ? btn('Continue to checkout', "go('checkout')", 'dark') : '')}${alertBox()}${state.cart.length ? `<div class="cart"><div>${state.cart.map(p => `<div class="cart-row"><div class="mini ${p.color}">${p.icon}</div><div><b>${p.name}</b><small>${p.type} · qty ${p.qty}</small><button onclick="remove('${p.id}')">Remove</button></div><strong>${money(p.price * p.qty)}</strong></div>`).join('')}</div><aside class="summary"><h2>Order summary</h2><p><span>Subtotal</span><b>${money(total())}</b></p><p><span>Shipping</span><span>${total() >= 75 ? 'Free' : '$8.00'}</span></p><p><span>Estimated tax</span><span>${money(total() * .08)}</span></p><hr/><h3><span>Total</span><b>${money(total() + (total() >= 75 ? 0 : 8) + total() * .08)}</b></h3>${btn('Checkout', "go('checkout')", 'dark wide')}</aside></div>` : `<div class="empty"><span>⌑</span><h2>Your bag is waiting.</h2><p>Fill it with something useful.</p>${btn('Start exploring', "go('shop')", 'dark')}</div>`}`); }
function checkoutPage() { return layout(`${heading('Checkout', 'Almost yours.', 'Secure checkout. We never store your card details.')}${alertBox()}<div class="checkout"><div class="forms"><section><h2>Contact information</h2><div class="form-grid"><label>Email<input value="you@example.com"/></label><label>Phone<input value="+1 207 555 0189"/></label></div></section><section><h2>Shipping address</h2><div class="form-grid"><label>First name<input value="Puru"/></label><label>Last name<input value="Sharma"/></label><label class="full">Address<input value="44 Pine Street"/></label><label>City<input value="Portland"/></label><label>Postal code<input value="04101"/></label></div></section><section><h2>Payment <small>Encrypted & secure</small></h2><label>Card number<input value="4242 4242 4242 4242"/></label><div class="form-grid"><label>Expiry<input value="09 / 28"/></label><label>CVC<input value="123"/></label></div></section>${btn('Place order', 'checkout()', 'dark wide')}</div><aside class="summary"><h2>Your order</h2>${(state.cart.length ? state.cart : [products[0]]).map(p => `<p><span>${p.name}<small>Qty ${p.qty || 1}</small></span><b>${money(p.price * (p.qty || 1))}</b></p>`).join('')}<hr/><h3><span>Total</span><b>${money((state.cart.length ? total() : products[0].price) * 1.08)}</b></h3></aside></div>`); }
function account() { return layout(`${heading('Your account', 'Welcome back, Puru.', 'Everything in one place.') }<div class="account-grid">${[['▣','Orders','Track deliveries and see past purchases.','orders'],['◯','Profile','Keep your details up to date.','profile'],['⌂','Addresses','Save time at checkout.','addresses'],['♢','Preferences','Choose what you hear from us.','preferences']].map(x => `<a href="#${x[3]}" onclick="go('${x[3]}');return false"><span>${x[0]}</span><b>${x[1]}</b><p>${x[2]}</p><small>Manage →</small></a>`).join('')}<button class="account-action" onclick="refresh()"><span>↻</span><b>Refresh session</b><p>Continue an existing session.</p><small>Sign in again →</small></button></div>`); }
function orders() { return layout(`${heading('Your account', 'Orders', 'A quiet record of things heading your way.') }<div class="orders"><a href="#order" onclick="go('order');return false"><b>#MB-20481</b><span class="tag green">Delivered</span><small>Mar 18, 2026</small><p><span class="mini sage">▱</span><span class="mini orange">◍</span> 2 items · $152.00 <strong>View →</strong></p></a><div><b>#MB-20192</b><span class="tag blue">In transit</span><small>Mar 04, 2026</small><p><span class="mini sand">◒</span> 1 item · $184.00</p></div></div>`); }
function order() { return layout(`${heading('Order #MB-20481', 'On its way.', 'Ordered March 18, 2026 · Delivered March 21, 2026', btn('Back to orders', "go('orders')"))}<div class="order-layout"><section class="tracking">${['Delivered · Left somewhere safe','Out for delivery · March 21','In transit · Portland, ME','Order placed · March 18'].map(x => `<div><i>✓</i><b>${x.split(' · ')[0]}</b><small>${x.split(' · ').slice(1).join(' · ')}</small></div>`).join('')}</section><aside class="summary"><h2>Order summary</h2><p><span>Items</span><b>2</b></p><p><span>Subtotal</span><b>$152.00</b></p><p><span>Shipping</span><span>Free</span></p><hr/><h3><span>Total</span><b>$152.00</b></h3>${btn('Start a return', "notice('Return request started')", 'wide')}</aside></div>`); }
function profile() { return layout(`${heading('Your account', 'Profile', 'Keep your details current so every order finds you.')}${alertBox()}<section class="form-card profile"><div class="avatar">PS</div><div class="form-grid"><label>First name<input value="Puru"/></label><label>Last name<input value="Sharma"/></label><label class="full">Email<input value="puru@example.com"/></label><label>Phone<input value="+1 207 555 0189"/></label><label>Birthday<input value="June 12"/></label></div>${btn('Save changes', 'profileSave()', 'dark')}</section>`); }
function addresses() { return layout(`${heading('Your account', 'Addresses', 'Save your favorite places.') }<div class="address-grid"><div><span class="tag blue">Default</span><b>Puru Sharma</b><p>44 Pine Street<br/>Portland, ME 04101<br/>United States</p><button onclick="notice('Address editor opened')">Edit address</button></div><div><b>Puru Sharma</b><p>18 Alder Lane<br/>Brooklyn, NY 11211<br/>United States</p><button onclick="notice('Address editor opened')">Edit address</button></div><button class="add-address" onclick="notice('Address editor opened')">＋<b>Add address</b></button></div>`); }
function preferences() { return layout(`${heading('Your account', 'Preferences', 'A little less inbox, a little more signal.') }<div class="preferences"><div><b>Seasonal notes</b><p>New collections, studio visits, and useful stories from outside.</p><label><input type="checkbox" checked/> Email me occasionally</label></div><div><b>Order updates</b><p>Shipping, delivery, and return notifications.</p><label><input type="checkbox" checked/> Always on</label></div><div><b>Product drops</b><p>Be the first to know when small batches arrive.</p><label><input type="checkbox"/> Tell me about new drops</label></div></div>${btn('Save preferences', "notice('Preferences saved')", 'dark')}`); }
function help() { return layout(`${heading('Customer care', 'How can we help?', 'A few answers before you need to ask.') }<div class="faqs">${['Shipping & delivery','Returns','Materials & care','Orders','Account'].map(x => `<button onclick="notice('Answer opened')"><span>${x}</span><b>How can we help with ${x.toLowerCase()}?</b><i>＋</i></button>`).join('')}</div><div class="help-call"><h2>Still curious?</h2><p>Our team is happy to help with the odd questions too.</p>${btn('Contact us', "go('contact')", 'dark')}</div>`); }
function contact() { return layout(`${heading('Customer care', 'Contact us', 'We read every message. Tell us a little about what you need.') }<div class="contact"><section class="form-card"><div class="form-grid"><label>Name<input value="Puru Sharma"/></label><label>Email<input value="puru@example.com"/></label><label class="full">Topic<select><option>Order question</option><option>Product question</option><option>Something went wrong</option></select></label><label class="full">Message<textarea placeholder="Tell us a little more..."></textarea></label></div>${btn('Send message', 'supportSend()', 'dark')}</section><aside><b>Email</b><span>hello@meanttobreak.example</span><b>Hours</b><span>Mon–Fri · 9am–5pm EST</span><b>Studio</b><span>44 Pine Street<br/>Portland, Maine</span></aside></div>`); }
function about() { return layout(`<section class="about"><small>Our story</small><h1>Keep the good.<br/><em>Leave the rest.</em></h1><p>Meant to Break began with a simple idea: everyday things should invite you outside, not ask you to replace them next season.</p></section><section class="values"><div><small>01</small><h2>Take the long view</h2><p>Good design should outlast the mood that brought it home.</p></div><div><small>02</small><h2>Make room outside</h2><p>The best objects help you spend less time arranging and more time doing.</p></div><div><small>03</small><h2>Stay human</h2><p>Small batches, real people, and an inbox you can actually reach.</p></div></section>`); }
function admin() { return layout(`${heading('Workspace', 'Operations', 'A simple view for the people behind the shop.', btn('View exports', "go('exports')", 'dark'))}<div class="stats"><div><span>Orders today</span><b>128</b><small>↑ 14% from yesterday</small></div><div><span>Open shipments</span><b>42</b><small>6 need attention</small></div><div><span>Inventory value</span><b>$84.2k</b><small>Across 38 SKUs</small></div><div><span>Support inbox</span><b>7</b><small>2 waiting today</small></div></div><div class="admin-columns"><section class="form-card"><h2>Recent orders</h2>${['#MB-20481 · Puru Sharma · Paid','#MB-20480 · Alice Kim · Ready','#MB-20479 · Mateo Brown · Shipped'].map(x => `<p class="admin-row">${x}</p>`).join('')}</section><section class="form-card"><h2>Quick actions</h2>${[['▦','Manage inventory','inventory'],['⌁','Fulfillment queue','fulfillment'],['↥','Export order data','exports']].map(x => `<button class="action-row" onclick="go('${x[2]}')">${x[0]} ${x[1]} <span>→</span></button>`).join('')}</section></div>`); }
function inventory() { return layout(`${heading('Workspace', 'Inventory', 'Keep the shelves honest.') }<section class="table"><h2>All products <small>8 active SKUs</small></h2><table><thead><tr><th>Product</th><th>SKU</th><th>Available</th><th>Status</th></tr></thead><tbody>${products.map((p,i) => `<tr><td><span class="mini ${p.color}">${p.icon}</span>${p.name}</td><td>MB-${String(i+1).padStart(3,'0')}</td><td>${[24,8,91,14,6,42,37,11][i]}</td><td><span class="tag ${i===1||i===4?'amber':'green'}">${i===1||i===4?'Low stock':'Healthy'}</span></td></tr>`).join('')}</tbody></table></section>`); }
function fulfillment() { return layout(`${heading('Workspace', 'Fulfillment', 'Every package tells a small story.') }<div class="tabs-line"><b>All 42</b><span>To pack 12</span><span>In transit 18</span><span>Delivered 12</span></div><div class="fulfillment">${['#MB-20481 · Puru Sharma','#MB-20480 · Alice Kim','#MB-20479 · Mateo Brown','#MB-20478 · Noor Patel'].map((x,i) => `<div><b>${x}</b><span class="tag ${i<2?'blue':'green'}">${i===0?'To pack':i===1?'Ready':'In transit'}</span><small>Updated ${i+2} min ago</small><button onclick="notice('Order marked ready')">Update</button></div>`).join('')}</div>`); }
function exportsPage() { return layout(`${heading('Workspace', 'Exports', 'Take a clean copy of the data when you need it.', btn('New export', 'exportData()', 'dark'))}${alertBox()}<section class="export"><div><h2>Order exports</h2><p>Exports are prepared in the background and appear here when ready.</p></div><div class="export-row"><b>orders-march-2026.csv</b><small>Created Mar 18 · 4.8 MB</small><button onclick="notice('Download started')">Download</button></div><div class="export-row"><b>inventory-snapshot.csv</b><small>Created Mar 01 · 122 KB</small><button onclick="notice('Download started')">Download</button></div></section>`); }
function render() { const pages = { home, shop, categories, category, product, search: searchPage, cart, checkout: checkoutPage, account, orders, order, profile, addresses, preferences, help, contact, about, admin, inventory, fulfillment, exports: exportsPage }; $('app').innerHTML = (pages[state.route] || home)(); }
window.addEventListener('hashchange', () => { state.route = location.hash.slice(1) || 'home'; render(); });
render();
